version: "3.8"

services:
  immich-server:
    build: .
    container_name: immich_main
    restart: unless-stopped
    volumes:
      - /data/main:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
      - immich-machine-learning
    environment:
      - UPLOAD_LOCATION=/data/library
      - DB_DATA_LOCATION=/data/postgres
      - DB_PASSWORD=immich_password
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - IMMICH_VERSION=release
      - REDIS_HOSTNAME=redis
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    restart: unless-stopped
    volumes:
      - /data/main/model-cache:/cache
    environment:
      - MACHINE_LEARNING_CACHE_FOLDER=/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: immich_redis
    restart: unless-stopped
    volumes:
      - /data/main/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: immich_password
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /data/main/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d immich -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    name: immich